### PR TITLE
bardburn

### PR DESCRIPTION
**Pull request by mhwicks**
song of stone is an aa so i fixed that, and added a song of rats :)

### CODE REVIEW

**Comment by mhwicks** [comment]
Yes that is why I changed it, cant look for it in the book and then /cast an AA

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by DynoDojo** [comment]
Yeah, but review the spell you added.


________________________________

**Comment by mhwicks** [comment]
Will look at it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by mhwicks** [comment]
Found out she was PB AE slow so that could cause her to die a lot 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by DynoDojo** [comment]
Please try again when ready.  the "alt" at the end of call cast tells it to use an AA, not a spell.

**Pull request closed without merging**
